### ISSUE TITLE
Can not use `AudioSource` with bevy_asset_loader on the latest main branch

### ISSUE THREAD

**Issue by developomp** [NiklasEi/bevy_kira_audio#58]
The following code fails to compile on the latest commit of `bevy_kira_audio` (b721820).
This issue is very similar to #31, however I can't find a commit that works for me. I absolutely need the feature introduced on [this commit](https://github.com/bevyengine/bevy/commit/fed93a0edce9d66586dc70c1207a2092694b9a7d), but no commit after this one compiles successfully.

I also do not understand why this error is thrown in the first place. [this code](https://github.com/NiklasEi/bevy_kira_audio/blob/b721820d0f7b479a136cc2a9d51c23bbedd2934e/src/source/mod.rs#L16) clearly shows that `TypeUuid` is defined for `AudioSource` so I'm not sure where the error is coming from.

Failing code:
- [NiklasEi/bevy_game_template](https://github.com/NiklasEi/bevy_game_template)
- `bevy` and `bevy_kira_audio` set to the latest commit

```rs
#[derive(AssetCollection)]
pub struct AudioAssets {
    #[asset(path = "audio/flying.ogg")]
    pub flying: Handle<AudioSource>,
}
```

Error:
```
error[E0277]: the trait bound `AudioSource: TypeUuid` is not satisfied
   --> src/loading.rs:34:17
    |
34  |     pub flying: Handle<AudioSource>,
    |                 ^^^^^^^^^^^^^^^^^^^ the trait `TypeUuid` is not implemented for `AudioSource`
    |
```

Cargo.toml
```toml
...

[features]
default = [
    "bevy_kira_audio/ogg",
    "bevy/bevy_winit",
    "bevy/render",
    "bevy/png",
    "bevy/x11",
]

dev = ["bevy/dynamic"]

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", rev = "7d554146524987b050923841de06c7d18adf66e9", default-features = false }
bevy_kira_audio = { git = "https://github.com/NiklasEi/bevy_kira_audio", rev = "b721820d0f7b479a136cc2a9d51c23bbedd2934e" }
bevy_asset_loader = "0.11.0"
rand = "0.8.5"

[target.'cfg(target_os = "linux")'.dependencies]
winit = { version = "0.26.1", features = ["x11"] }

[build-dependencies]
embed-resource = "1.7.2"

...
```
